name: react-in-angular-$(variables['packVer'])

stages:
  - stage: Build
    jobs:
      - job: 
        steps:
          - checkout: self

          - task: Npm@1
            inputs:
              command: 'ci'
         
          - script: |
              $version=$(cat package.json | jq -r .version)
              echo "##vso[task.setvariable variable=packVer;]$version"

          - task: Npm@1
            inputs:
              command: 'custom'
              customCommand: 'run build'
