name: react-in-angular

stages:
  - stage: Build
    jobs:
      - job: 
        steps:
          - checkout: self

          - task: Npm@1
            inputs:
              command: 'ci'
                
          - task: Npm@1
            inputs:
              command: 'custom'
              customCommand: 'run build'